M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Do 02 Mai 2024 22:23:52
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2024-05-02T22:23:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X122784Y-124090
X122784Y-131090
M30
